export const actionTypes = {
  GET_PRODUCT_BEGIN: "GET_PRODUCT_BEGIN",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",
  GET_CATEGORY_BEGIN: "GET_CATEGORY_BEGIN",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  TOGGLE_TOP_MENU: "TOGGLE_TOP_MENU",
  TOGGLE_DISPLAY_LIST: "TOGGLE_DISPLAY_LIST",
  TOGGLE_DISPLAY_PRODUCT: "TOGGLE_DISPLAY_PRODUCT",
  SET_ACTIVE_SUB_CATEGORY: "SET_ACTIVE_SUB_CATEGORY",

  SET_AUTH_USER: "SET_AUTH_USER",
  SET_USER: "SET_USER"
};
export const targets = {
  HOME_PAGE: "HOME_PAGE",
  PRODUCT_LIST_PAGE: "PRODUCT_LIST_PAGE"
};
