export const actionTypes = {
  GET_PRODUCT_BEGIN: "GET_PRODUCT_BEGIN",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE"
};
export const targets = {
  HOME_PAGE: "HOME_PAGE",
  PRODUCT_PAGE: "PRODUCT_PAGE"
};
