export const actionTypes = {
  GET_PRODUCT_BEGIN: "GET_PRODUCT_BEGIN",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

  GET_CATEGORY_BEGIN: "GET_CATEGORY_BEGIN",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",

  GET_RATING_BEGIN: "GET_RATING_BEGIN",
  GET_RATING_SUCCESS: "GET_RATING_SUCCESS",
  GET_RATING_FAILURE: "GET_RATING_FAILURE",

  SET_RATING_BEGIN: "SET_RATING_BEGIN",
  SET_RATING_SUCCESS: "SET_RATING_SUCCESS",
  SET_RATING_FAILURE: "SET_RATING_FAILURE",

  TOGGLE_TOP_MENU: "TOGGLE_TOP_MENU",
  TOGGLE_DISPLAY_LIST: "TOGGLE_DISPLAY_LIST",
  TOGGLE_DISPLAY_PRODUCT: "TOGGLE_DISPLAY_PRODUCT",
  SET_ACTIVE_SUB_CATEGORY: "SET_ACTIVE_SUB_CATEGORY",

  SET_AUTH_USER: "SET_AUTH_USER",
  SET_USER: "SET_USER",

  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART"
};
export const targets = {
  HOME_PAGE: "HOME_PAGE",
  PRODUCT_LIST_PAGE: "PRODUCT_LIST_PAGE",
  PRODUCT_DETAIL_PAGE: "PRODUCT_DETAIL_PAGE"
};
